### ISSUE TITLE
The code

### ISSUE THREAD

**Issue by ghost** [corvusheretic/Binarization-of-documents#1]
@corvusheretic Can you post the source code

**Comment by corvusheretic** [comment]
Code added to git now. Details on the experiments can be found in our paper.
http://uu.diva-portal.org/smash/get/diva2:770839/FULLTEXT01.pdf

I have worked on improving these ideas further using Deep learning. Papers and the code for these can be found here
Papers:
http://uu.diva-portal.org/smash/get/diva2:1162457/FULLTEXT01.pdf
https://arxiv.org/abs/1801.08694

Code:
https://github.com/krayyalasomayajula/pdNet

**Comment by ghost** [comment]
@corvusheretic Thanks man. Also how to compile and use, would be amazing.

**Comment by corvusheretic** [comment]
> @corvusheretic Thanks man. Also how to compile and use, would be amazing.

The README.md file has been updated with basic instructions to run the experiments.
